services:

  db:
    image: postgres:14
    container_name: onboarding_db
    restart: always
    environment:
      POSTGRES_DB: onboarding
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    networks:
      - onboarding_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: onboarding_backend
    restart: always
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql://postgres:admin123@db:5432/onboarding
      FLASK_DEBUG: "False"
      FRONTEND_URL: "http://44.222.194.21"
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - onboarding_network

  admin:
    build:
      context: ./backend
      dockerfile: Dockerfile.admin
    container_name: onboarding_admin
    restart: always
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql://postgres:admin123@db:5432/onboarding
      FLASK_DEBUG: "False"
      FRONTEND_URL: "http://44.222.194.21"
    depends_on:
      - db
    ports:
      - "5001:5001"
    networks:
      - onboarding_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: onboarding_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - onboarding_network

volumes:
  db_data:

networks:
  onboarding_network:
    driver: bridge

